version: "3.8"


secrets:
    prefect-key:
        external: true                  # PROD
        # file: ./secrets/prefect-key   # TESTING

services:
    prefect-agent:
        image: ghcr.io/darrida/prefect-agent:2.1.1-py3.10-arm64-slim
        environment:
            - PREFECT_API_BASE_URL=https://api.prefect.cloud
            - PREFECT_ACCOUNT_ID=<ID>
            - PREFECT_WORKSPACE_ID=<ID>
            - PREFECT_PROFILE=default
            - PREFECT_WORK_QUEUES=prod,pprd,default
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname==pi4-node1
        secrets:
            - prefect-key
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"    