# FROM --platform=linux/arm64 prefecthq/prefect:2.1.1-python3.10
FROM --platform=linux/arm64 arm64v8/python:3.10.6-bullseye
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN     apt-get update && apt-get upgrade -y
RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN     curl -fsSL https://get.docker.com | sh

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version

ADD ./environment.yaml environment.yaml
RUN conda create --name prefect-2-agent --file ./environment.yaml --prefix ./env


FROM --platform=linux/arm64 arm64v8/python:3.10.6-slim-bullseye as application
COPY --from=build venv venv

ADD     ./startup.sh startup.sh
ADD     ./work_queues_list.py work_queues_list.py
RUN     chmod +x startup.sh

ENTRYPOINT ["bash", "startup.sh"]